cas_connect:
    path:     /connect
    defaults: { _controller: Vib94CasBundle:Default:connect }

cas_connect_check:
    path:     /connect_check
    defaults: { _controller: Vib94CasBundle:Default:connectCheck }