services:
#    cas.example:
#        class: Cas\CasBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    cas.authenticator:
        class: Vib94\CasBundle\Security\CasAuthenticator
        arguments: ["@security.token_storage", "@router", "@doctrine.orm.entity_manager", "%cas%"]
        autowire: true

    Vib94\CasBundle\Security\CasAuthenticator: '@cas.authenticator'
#    AppBundle\Security\CasTokenAuthenticator:
#        arguments:
#            $token_storage: "@security.token_storage"
#            $aut_checker: "@security.authorization_checker"
#            $router: "@router"
#            $em: "@doctrine.orm.entity_manager"
#            $casHost: 'auth.ville-creteil.intra'
#            $casPort: 80
#            $context: '/cas'
#            $validate: '/cas/serviceValidate'
#            $debug: false
#            $verif: false